services:
  db:
    image: docker.io/postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: eshop
      POSTGRES_PASSWORD: development
    ports:
      - 5432:5432

  adminer:
    image: docker.io/adminer
    restart: always
    ports:
      - 8080:8080