// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"github.com/gofrs/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Event struct {
	EventID        int64
	StreamID       uuid.UUID
	IdempotencyKey uuid.UUID
	RecordedAt     pgtype.Timestamptz
	Version        int64
	Payload        []byte
}

type Stream struct {
	StreamID       uuid.UUID
	IdempotencyKey uuid.UUID
	LatestVersion  int64
}
